apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: k8s
  labels:
    app: react-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    # targetPort: 3000
  selector:
    app: react-app
