apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: k8s
  labels:
    app: java-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003
  selector:
    app: java-app
